name:                write-you-a-scheme
version:             0.1.0.0
github:              "githubuser/write-you-a-scheme"
license:             BSD3
author:              "4afS"
maintainer:          "4afs.h1@gmail.com"
copyright:           "2022 4afS"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/write-you-a-scheme#readme>

dependencies:
- base >= 4.7 && < 5
- text > 1.2
- containers > 0.6
- mtl > 2.2
- parsec > 3.1
- hspec > 2
- neat-interpolation

library:
  source-dirs: src

executables:
  write-you-a-scheme-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - write-you-a-scheme

tests:
  write-you-a-scheme-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - write-you-a-scheme
